# Generated by Django 2.0.7 on 2018-11-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('cover', models.TextField()),
                ('markdownContent', models.TextField()),
                ('time', models.CharField(max_length=50)),
                ('readTimes', models.IntegerField()),
            ],
        ),
    ]
